# Top-level Makefile — ATHAD (Atmosphere of the Earth in the Hadean Eon)
# Builds the atmosphere model, the Python interface and the CLI interface.
# Forked from ATOM_Precipitation @ 1e3f319; the hydrosphere half is not part of ATHAD.

# -MMD -MP emits a .d file per object listing the headers it includes, so editing a
# header rebuilds every .cpp that pulls it in. Without this the build silently keeps
# stale objects — and ATHAD's physics lives almost entirely in headers (ThermoAtm.h,
# MoistConvection.h, SaturationAdjustment.h, MultiLayerRadiation.h, TurbulenceAtm.h),
# so a header edit that does not recompile is the normal case, not the exception.
CFLAGS = -ggdb -Wall -ffast-math -march=native -fPIC -std=c++17 -Ilib -Iatmosphere -Itinyxml2 -fopenmp -MMD -MP

# Common files for the shared lib(libathad.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATM_OBJ = atmosphere/cAtmosphereModel.o atmosphere/PrintMsg_Atm.o \
atmosphere/FileIO_Atm.o atmosphere/RHS_Atm_Turb.o \
atmosphere/RungeKutta_Atm_Turb.o atmosphere/MinMax_Atm.o \
atmosphere/Paraview_Atm.o atmosphere/InitValues_Atm.o \
atmosphere/Results_Atm.o

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATM_CLI_OBJ = cli/had.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = atmosphere/cAtmosphereDefaults.cpp.inc atmosphere/AtmosphereLoadConfig.cpp.inc \
atmosphere/AtmosphereParams.h.inc python/atmosphere_pxd.pxi python/pyathad.pyx \
python/config_athad.xml cli/config_athad.xml

COPY_FILE = pyathad.so
TARGET_DIR = python

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: had python $(target)

libathad.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATM_OBJ) $(XML_OBJ)
	ar rcs libathad.a $(LIB_OBJ) $(ATM_OBJ) $(XML_OBJ)

had: libathad.a $(ATM_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATM_CLI_OBJ) -L. -lathad $(cFLAGS) -o cli/had

$(PARAM_OUTPUTS): param.py
	rm -f atmosphere/cAtmosphereModel.o
	python param.py

analyze:
	analyze-build make

python: libathad.a python/pyathad.so

python/pyathad.so: python/pyathad.pyx python/athad.pxd libathad.a
	cd python && python setup.py build_ext --inplace

atmosphere/%.o: atmosphere/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

# Header dependencies emitted by -MMD, one .d per object. The '-' suppresses the
# "no such file" noise on the first build, before any .d exists.
DEPS = $(LIB_OBJ:.o=.d) $(ATM_OBJ:.o=.d) $(XML_OBJ:.o=.d) $(ATM_CLI_OBJ:.o=.d)
-include $(DEPS)

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATM_OBJ) $(XML_OBJ) $(ATM_CLI_OBJ) $(DEPS) $(PARAM_OUTPUTS) cli/had libathad.a
	\rm -vf python/*.so python/*.o python/pyathad.cpp
	\rm -rf python/build/
